# Generated by Django 3.1.5 on 2021-01-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('dashboard', '0001_repository_model_added'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='repositories',
            field=models.ManyToManyField(to='dashboard.Repository'),
        ),
    ]
