# Generated by Django 3.1.5 on 2021-01-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='repositories',
            field=models.ManyToManyField(to='repository.Repository'),
        ),
    ]
