# Generated by Django 3.1.5 on 2021-02-04 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_siteuser_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='repositories',
        ),
    ]
