version: '3.9'

services:
  db:
    restart: always
    image: postgres
    container_name: uks_db
    volumes:
    - ./pgdata:/var/lib/posgresql/data
    ports:
    - "8001:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  web:
    container_name: uks_web
    build: .
    command: ["./wait_for_postgres.sh"]
    expose:
      - 8000
    volumes:
      - ./static:/uks/static
    logging:
      driver: "json-file"
    depends_on:
      - db
      - es
      - kibana
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - SECRET_KEY=some_secret_key
      - DEBUG_MODE=True

  nginx:
    image: nginx
    container_name: uks_nginx
    ports:
      - "8000:8000"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/uks/static
    depends_on:
      - web

  # ELK stack for logging
  es:
    labels:
      com.example.service: "es"
      com.example.description: "For searching and indexing data"
    image: elasticsearch:5.4
    container_name: uks_es
    volumes:
      - ./esdata:/usr/share/elasticsearch/data/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  kibana:
    labels:
      com.example.service: "kibana"
      com.example.description: "Data visualisation and for log aggregation"
    image: kibana:5.4.3
    container_name: uks_kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://es:9200
    depends_on:
      - es

  logstash:
    labels:
      com.example.service: "logstash"
      com.example.description: "For logging data"
    image: logstash:5.4.3
    container_name: uks_logstash
    volumes:
      - ./config/logstash:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf
    depends_on:
      - es
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - "5959:5959"
