version: '3.9'

services:
  db:
    restart: always
    image: postgres
    container_name: uks_db
    volumes:
    - ./pgdata:/var/lib/posgresql/data
    ports:
    - "8001:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  web:
    container_name: uks_web
    build: .
    command: ["./wait_for_postgres.sh"]
    expose:
      - 8000
    # ports:
    #   - "8000:8000"
    volumes:
      - ./static:/uks/static
#    logging:
#      driver: "json-file"
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  nginx:
    image: nginx
    container_name: uks_nginx
    ports:
      - "8000:8000"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/uks/static
    depends_on:
      - web
