# Generated by Django 3.1.5 on 2021-02-11 14:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiki',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
