# Generated by Django 3.1.5 on 2021-01-30 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repository', '0001_initial'),
        ('security', '0003_siteuser_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('issue_status', models.CharField(choices=[('TODO', 'To do'), ('ONGOING', 'Ongoing'), ('DONE', 'Done')], default='TODO', max_length=8)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.repository')),
                ('site_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.siteuser')),
            ],
        ),
        migrations.CreateModel(
            name='IssueChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue.issue')),
            ],
        ),
    ]
