# Generated by Django 3.1.5 on 2021-02-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_status',
            field=models.CharField(choices=[('TODO', 'To do'), ('ONGOING', 'Ongoing'), ('DONE', 'Done'), ('CLOSED', 'Closed')], default='TODO', max_length=8),
        ),
    ]
