# Generated by Django 3.1.5 on 2021-02-03 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_siteuser_profile_img'),
        ('issue', '0002_auto_20210202_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='site_user',
        ),
        migrations.AddField(
            model_name='issue',
            name='assignees',
            field=models.ManyToManyField(related_name='assignees', to='security.SiteUser'),
        ),
        migrations.AddField(
            model_name='issue',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='security.siteuser'),
            preserve_default=False,
        ),
    ]
