# Generated by Django 3.1.5 on 2021-02-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0004_auto_20210203_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
