# Generated by Django 3.1.5 on 2021-02-04 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issue', '0005_auto_20210203_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assignees', to=settings.AUTH_USER_MODEL),
        ),
    ]
