# Generated by Django 3.1.5 on 2021-02-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0006_auto_20210204_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='closed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_status',
            field=models.CharField(choices=[('TODO', 'To do'), ('ONGOING', 'Ongoing'), ('DONE', 'Done')], default='TODO', max_length=8),
        ),
    ]
