# Generated by Django 3.1.5 on 2021-02-04 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milestone', '0001_initial'),
        ('issue', '0007_auto_20210204_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='milestone',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='milestone.milestone'),
            preserve_default=False,
        ),
    ]
