# Generated by Django 3.1.5 on 2021-02-12 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0011_issue_project'),
        ('issue', '0011_issue_labels'),
    ]

    operations = [
    ]
