# Generated by Django 3.1.5 on 2021-02-13 09:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0012_merge_20210212_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
