# Generated by Django 3.1.5 on 2021-02-15 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0013_auto_20210213_1024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IssueChange',
        ),
    ]
