# Generated by Django 3.1.5 on 2021-02-18 17:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0014_delete_issuechange'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='date_created',
            field=models.DateTimeField(verbose_name='Date of creation'),
            preserve_default=False,
        ),
    ]
