# Generated by Django 3.1.5 on 2021-02-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0015_issue_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='date_closed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date closed'),
        ),
    ]
