# Generated by Django 3.1.5 on 2021-02-15 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commit', '0001_initial'),
        ('branch', '0002_auto_20210205_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='commit.commit'),
        ),
    ]
