# Generated by Django 3.1.5 on 2021-01-30 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '0003_siteuser_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('dateChanged', models.DateTimeField()),
                ('belongsTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.siteuser')),
            ],
        ),
    ]
