# Generated by Django 3.1.5 on 2021-02-13 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wiki', '0004_delete_wikihistoryitem'),
        ('repository', '0003_merge_20210209_1703'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_changed', models.DateTimeField()),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('changed_repo_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.repository')),
                ('changed_wiki_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.wiki')),
            ],
        ),
        migrations.DeleteModel(
            name='UserHistoryItem',
        ),
    ]
