# Generated by Django 3.1.5 on 2021-02-12 15:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_auto_20210210_1118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserHistoryItem',
            new_name='HistoryItem',
        ),
    ]
