# Generated by Django 3.1.5 on 2021-02-15 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0014_delete_issuechange'),
        ('user', '0002_auto_20210213_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyitem',
            name='changed_issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='issue.issue'),
        ),
    ]
