# Generated by Django 3.1.5 on 2021-02-12 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_delete_wikihistoryitem'),
        ('repository', '0003_merge_20210209_1703'),
        ('user', '0003_auto_20210212_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyitem',
            name='changed_repo_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.repository'),
        ),
        migrations.AddField(
            model_name='historyitem',
            name='changed_wiki_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.wiki'),
        ),
    ]
