# Generated by Django 3.1.5 on 2021-02-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='dateCreated',
            field=models.DateField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='dateUpdated',
            field=models.DateField(auto_now_add=True, verbose_name='Last updated'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='dueDate',
            field=models.DateField(verbose_name='Due date'),
        ),
    ]
