# Generated by Django 3.1.5 on 2021-02-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestone', '0003_auto_20210207_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='dateClosed',
            field=models.DateField(blank=True, null=True, verbose_name='Date closed'),
        ),
    ]
