# Generated by Django 3.1.5 on 2021-02-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL to commit')),
                ('sha', models.TextField()),
                ('author', models.CharField(max_length=60)),
                ('date', models.DateTimeField()),
                ('message', models.TextField()),
                ('parents', models.ManyToManyField(related_name='_commit_parents_+', to='commit.Commit')),
            ],
        ),
    ]
