# Generated by Django 3.1.5 on 2021-02-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='parents',
            field=models.ManyToManyField(to='commit.Commit'),
        ),
    ]
