# Generated by Django 3.1.5 on 2021-02-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_auto_20210205_1629'),
        ('commit', '0002_auto_20210215_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='branches',
            field=models.ManyToManyField(to='branch.Branch'),
        ),
    ]
