# Generated by Django 3.1.5 on 2021-01-28 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('milestone', '0002_milestone_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.repository'),
        ),
    ]
