# Generated by Django 3.1.5 on 2021-02-09 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20210204_0836'),
        ('repository', '0002_repository_repo_url'),
    ]

    operations = [
    ]
