# Generated by Django 3.1.5 on 2021-02-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_merge_20210209_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='repo_url',
            field=models.CharField(blank=True, default='https://github.com/vtanja/UKS', max_length=100, null=True),
        ),
    ]
