# Generated by Django 3.1.5 on 2021-02-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20210215_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='repo_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
