# Generated by Django 3.1.5 on 2021-02-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20210215_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
