# Generated by Django 3.1.5 on 2021-02-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_auto_20210217_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
