# Generated by Django 3.1.5 on 2021-02-19 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_repository_visibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='visibility',
            new_name='public',
        ),
    ]
